# Generated by Django 2.1.4 on 2018-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181210_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airkoreadata',
            name='datatime',
            field=models.DateTimeField(blank=True, db_column='dataTime', null=True),
        ),
    ]
