# Generated by Django 2.1.4 on 2018-12-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181210_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airkoreadata',
            name='covalue',
            field=models.TextField(blank=True, db_column='coValue', null=True),
        ),
        migrations.AlterField(
            model_name='airkoreadata',
            name='no2value',
            field=models.TextField(blank=True, db_column='no2Value', null=True),
        ),
        migrations.AlterField(
            model_name='airkoreadata',
            name='o3value',
            field=models.TextField(blank=True, db_column='o3Value', null=True),
        ),
    ]
