# Generated by Django 2.1.4 on 2018-12-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181213_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airkoreadata',
            name='stnaddr',
        ),
        migrations.RemoveField(
            model_name='airkoreadata',
            name='stnname',
        ),
        migrations.AddField(
            model_name='airkoreadata',
            name='stnfk',
            field=models.ForeignKey(blank=True, db_column='stnfk', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.AirKoreaStations'),
        ),
    ]
