# Generated by Django 2.1.4 on 2018-12-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181213_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airkoreadata',
            name='stnfk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.AirKoreaStations'),
        ),
    ]
